FROM debian

RUN apt -y update \
    && apt -y install \
    git \
    make \
    pandoc \
    texlive-base \
    texlive-latex-extra \
    && rm -rf /var/lib/apt/lists/*
# # RUN useradd -G sudo -m vscode
# # USER vscode